"""
Site configuration for Antibody Trial Predictor reports

This file contains all static/configurable content that doesn't change
based on data. Update this file to change project branding, navigation,
colors, or other static text across all reports.
"""

SITE_CONFIG = {
    # Project Information
    'project': {
        'name': 'Antibody Clinical Trial Success Prediction',
        'code': 'Duke AIPI 520 Project 2',
        'copyright_year': 2025,
        'footer_text': 'Generated by ML Pipeline • Duke AIPI 520',
        'footer_subtext': 'Powered by Plotly & Python',
    },

    # Navigation
    'navigation': [
        {
            'id': 'overview',
            'label': 'Overview',
            'icon': '⭐',
            'url': 'index.html',
        },
        {
            'id': 'raw',
            'label': 'Raw Data EDA',
            'icon': '🔍',
            'url': 'eda_raw_data.html',
        },
        {
            'id': 'features',
            'label': 'Feature EDA',
            'icon': '🔬',
            'url': 'eda_features.html',
        },
    ],

    # Color Scheme (CSS variables)
    'colors': {
        'primary_blue': '#005587',
        'primary_teal': '#339898',
        'primary_cyan': '#1D6363',
        'accent_orange': '#C84E00',
        'accent_emerald': '#A1B70D',
        'bg_primary': '#f8fafc',
        'bg_secondary': '#e2e8f0',
        'bg_card': '#ffffff',
        'text_primary': '#1e293b',
        'text_body': '#334155',
        'text_secondary': '#64748b',
        'text_muted': '#94a3b8',
    },

    # Default Metadata
    'defaults': {
        'data_source': 'ClinicalTrials.gov API',
        'workflow_url_text': 'View on GitHub Actions',
    },

    # Overview Page Content
    'overview_content': {
        'project_overview': {
            'title': 'Project Overview',
            'description': 'Real-world ML challenge: predicting clinical trial success for antibody therapeutics',
            'problem_statement': {
                'title': 'Problem Statement',
                'tooltip_title': 'Why Antibody Trials?',
                'tooltip_text': 'Antibodies represent ~30% of the pharmaceutical development pipeline with high commercial value ($237B+ market), but face historically high failure rates.',
                'text': 'Predict probability of success for Phase 2 & 3 antibody clinical trials. With {failure_rate}% failure rate observed in our dataset and costs of $10-100M+ per trial, early prediction can save pharmaceutical companies significant resources.',
            },
            'data_source': {
                'title': 'Data Source',
                'primary': 'ClinicalTrials.gov Bulk XML Download',
                'secondary': 'Streaming parse from S3-hosted bulk XML archive',
                'details': 'Phase 2/3 interventional antibody trials (completed/terminated/withdrawn status)',
            },
            'success_labeling': {
                'title': 'Success Labeling Strategy',
                'subtitle': 'Refined Binary Classification:',
                'success_label': 'Success (1):',
                'success_criteria': 'COMPLETED, APPROVED_FOR_MARKETING, AVAILABLE',
                'failure_label': 'Failure (0):',
                'failure_criteria': 'TERMINATED/WITHDRAWN/SUSPENDED for efficacy or safety reasons',
                'excluded_label': 'Excluded:',
                'excluded_criteria': 'Trials terminated for administrative reasons (funding, enrollment, business decisions)',
                'note': 'This approach focuses on efficacy outcomes rather than administrative completion.',
            },
        },
        'dataset_stats': {
            'title': 'Dataset Statistics',
            'sample_counts': {
                'title': 'Sample Counts',
                'total_label': 'Total Samples:',
                'train_label': 'Training Set:',
                'test_label': 'Test Set:',
            },
            'class_distribution': {
                'title': 'Class Distribution (Test Set)',
                'failure_label': 'Failure (Class 0):',
                'success_label': 'Success (Class 1):',
            },
            'data_quality': {
                'title': 'Data Quality',
                'source_label': 'Source:',
                'source_value': 'ClinicalTrials.gov Bulk XML (S3)',
                'validation_label': 'Validation:',
                'validation_value': 'Random stratified train/test split (80/20)',
                'features_label': 'Features:',
                'features_value': '32 domain-specific engineered features',
            },
        },
        'feature_engineering': {
            'title': 'Feature Engineering - 32 Features',
            'subtitle': 'Domain-specific feature set:',
            'feature_groups': [
                'Antibody Type & Mechanism (12 features)',
                'Trial Design & Enrollment (8 features)',
                'Disease Categories (8 features)',
                'Sponsor Characteristics (3 features)',
                'Temporal Features (4 features + has_start_date flag)',
                'Trial Metadata (1 feature)',
            ],
            'antibody_features': 'Type classification (murine/chimeric/humanized/fully_human), target mechanisms (checkpoint inhibitors, growth factors, cytokines, CD markers), biomarker selection, combination therapy indicators',
            'methodology': 'Post-2024 trials filtered (22), text features excluded, has_start_date flag for missing dates (45%), stratified random split',
        },
        'model_performance': {
            'title': 'Model Performance Summary',
            'description': 'Comprehensive comparison of all 5 models across key metrics',
            'table_headers': ['Model', 'Accuracy', 'Precision', 'Recall', 'F1 Score', 'ROC AUC', 'CV ROC AUC (Mean ± Std)', 'Training Time'],
        },
        'metrics_comparison': {
            'title': 'Performance Metrics Comparison',
            'description': 'Interactive visualization of model performance across all evaluation metrics',
        },
        'cv_results': {
            'title': 'Cross-Validation Results',
            'description': 'Model consistency evaluated through 3-fold stratified cross-validation',
        },
        'feature_importance': {
            'title': 'Feature Importance Analysis',
            'description': 'Most influential features for predicting clinical trial success using the best model ({model_name})',
        },
        'confusion_matrices': {
            'title': 'Confusion Matrices',
            'description': 'Detailed breakdown of predictions vs. actual outcomes for each model',
            'note': 'Values show absolute counts with percentages. Class 0 = Failure | Class 1 = Success',
        },
    },
}
